name: Linters
on:
  - pull_request
jobs:
  vale:
    name: vale
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Asciidoctor
        run: sudo apt-get install -y asciidoctor
      - name: Vale Linter
        uses: errata-ai/vale-action@reviewdog
        with:
          vale_flags: "--minAlertLevel=error"
          fail_on_error: true
        env:
          # Required, set by GitHub actions automatically:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
